spring:
  application:
    name: graphql-java-tools-app
server:
  port: 9001
graphql:
  servlet:
    exception-handlers-enabled: true
graphiql:
  headers:
    Authorization: "Bearer 05bd9a5f3fe0408f89520946b0fe1b06"
  props:
    variables:
      headerEditorEnabled: true
logging:
  level:
    com:
      oembedler:
        moon:
          graphql:
            boot:
              error: debug
