spring:
  application:
    name: graphql-todo-app
  servlet:
    multipart:
      enabled: true
      location: /tmp
  main:
    allow-bean-definition-overriding: true
server:
  port: 9000
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
graphql:
  servlet:
    actuator-metrics: true
  playground:
    enabled: true
    cdn:
      enabled: false
      version: latest
  altair:
    enabled: true
    cdn:
      enabled: false
      version: 4.0.2
  graphiql:
    enabled: true
    cdn:
      enabled: false
      version: 0.17.5
    headers:
      Test: TestHeader
    props:
      variables:
        headerEditorEnabled: true
        headers: '{ "Authorization": "SomeValue" }'
  voyager:
    enabled: true
    cdn:
      enabled: false
